
using Content.Client.UserInterface.Controls;
using Content.Shared.SmartFridge;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SmartFridge.UI;

[GenerateTypedNameReferences]
public sealed partial class SmartFridgeMenuItem : PanelContainer
{
    public SmartFridgeInventoryEntry? Item;
    public SmartFridgeMenuItem()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }
}
