
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.SmartFridge.UI;

[GenerateTypedNameReferences]
public sealed partial class SmartFridgeMenuCatagory : BoxContainer
{

}
