using Content.Client.UserInterface.Controls;
using Content.Shared.SmartFridge;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using System.Numerics;

namespace Content.Client.SmartFridge.UI;

[GenerateTypedNameReferences]
public sealed partial class SmartFridgeMenu : FancyWindow
{
    [Dependency] private readonly EntityManager _entityManager = default!;

    public SmartFridgeMenu()
    {
        MinSize = SetSize = new Vector2(250, 150);
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // SmartFridgeItems.AddItem("TEST ITEM");

        // foreach (var item in SmartFridgeItems)
        // {

        // }
    }

    public void Populate(List<SmartFridgeInventoryGroup> entities)
    {
        SmartFridgeItems.RemoveAllChildren();

        foreach (var group in entities)
        {
            var catagory = new SmartFridgeMenuCatagory();
            catagory.CatagoryName.Text = group.Name;

            // TODO: List entries!
            foreach (var item in group.Items)
            {
                if (!_entityManager.TryGetEntity(item.Entity, out var uid))
                {
                    continue;
                }

                var uiItem = new SmartFridgeMenuItem();
                uiItem.ItemName.Text = _entityManager.GetComponent<MetaDataComponent>(uid.Value).EntityName;

                catagory.Contents.AddChild(uiItem);
            }
            SmartFridgeItems.AddChild(catagory);
        }
    }
}
