using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;

namespace Content.Client.Chemistry.UI;

[GenerateTypedNameReferences]
public sealed partial class ChemiCompilerWindow : FancyWindow
{

}

